"""
Generate web/data.js from the latest episode pair + supervisor log.
Usage: python scripts/export_demo.py
       python scripts/export_demo.py --video-base https://your-cdn.com/videos
"""
import sys
import json
import argparse
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

parser = argparse.ArgumentParser()
parser.add_argument("--video-base", default="videos", help="base URL/path for video files")
args = parser.parse_args()

episodes = Path("outputs/episodes")
logs = sorted(episodes.glob("???_log.json"))
if not logs:
    print("no log files found — run scripts/run_rung3.py first")
    sys.exit(1)

latest = json.loads(logs[-1].read_text())
prefix = logs[-1].stem.replace("_log", "")

unsup_name = f"{prefix}_unsupervised.mp4"
sup_name   = f"{prefix}_supervised.mp4"

data = {
    "unsupervised_video": f"{args.video_base}/{unsup_name}",
    "supervised_video":   f"{args.video_base}/{sup_name}",
    "unsupervised_steps": latest["unsupervised_steps"],
    "supervised_steps":   latest["supervised_steps"],
    "retries":            latest["retries"],
    "cerebras_model":     "gemma-4-31b",
    "supervisor_log":     latest["supervisor_log"],
}

out = Path("web/data.js")
out.write_text(f"// Generated by scripts/export_demo.py — episode {prefix}\nconst DEMO = {json.dumps(data, indent=2)};\n")
print(f"wrote {out} (episode {prefix}, {len(data['supervisor_log'])} supervisor calls)")
print(f"video base: {args.video_base}")
print(f"\nFor local preview: copy mp4s to web/videos/ then open web/index.html")
print(f"For Vercel: python scripts/export_demo.py --video-base https://your-cdn/videos")
