// Generated by scripts/export_demo.py — episode 007
const DEMO = {
  "unsupervised_video": "videos/007_unsupervised.mp4",
  "supervised_video": "videos/007_supervised.mp4",
  "unsupervised_steps": 1350,
  "supervised_steps": 2351,
  "retries": 2,
  "cerebras_model": "gemma-4-31b",
  "supervisor_log": [
    {
      "step": 500,
      "signals": {
        "gripper_closed_empty": true,
        "cube_out_of_region": false,
        "no_progress": false
      },
      "correction": {
        "failure_type": "gripper_missed",
        "diagnosis": "The gripper closed but failed to secure the green cube, leaving it on the table.",
        "corrected_instruction": "Open the gripper, reposition the arm directly above the center of the green cube, and attempt to grasp it again."
      }
    },
    {
      "step": 1000,
      "signals": {
        "gripper_closed_empty": true,
        "cube_out_of_region": false,
        "no_progress": false
      },
      "correction": {
        "failure_type": "gripper_missed",
        "diagnosis": "The gripper closed without grasping the cube because it was not properly aligned or deep enough.",
        "corrected_instruction": "Re-center the gripper directly over the green cube, descend slightly further, and attempt to grasp it again."
      }
    }
  ]
};
